# PrettyTable
from prettytable import PrettyTable
임포트 하고 PrettyTable 객체르 만들어 사용했다.

```python
table = PrettyTable()
table.field_names = ["번호", "이름", "타입"]
for pokemon in pokemon_data:
    table.add_row(pokemon)
# table.add_rows(pokemon_data)
print(table)0
```
이런식으료 포 만들수 있음.

공식 문서 보고 궁금해서 하나씩 써보면서 익혔다
```python
# 표에 padding 주는거
table.padding_width=4
# 표 스타일 정해주는거 TableStyle 도 import 해야함
table.set_style(TableStyle.DOUBLE_BORDER)
# 테이블 이름이랑 자동 번호 설정해줌 1부터
table.add_autoindex("번호")
# 테이블을 각종 format 으로 문자열로 뽑아줌
print(table.get_formatted_string(out_format="html"))
```
TableStyle 을 사용하기위해
from prettytable import TableStyle
이것도 임포트 해줬었다
표에 패딩 주거나 표 스타일 바꾸고
자동 번호 설정해주는거
문자열로 뽑아주는거
추후 html 사용할때 복잡한 표 만들 일 이 생기면 파이썬으로 해도 될듯
```python
pokemon_num = []
pokemon_name = []
pokemon_type = []
for pokemon in pokemon_data:
    pokemon_num.append(pokemon[0])
    pokemon_name.append(pokemon[1])
    pokemon_type.append(pokemon[2])
table.add_column("번호",pokemon_num,"c","t")
table.add_column("이름",pokemon_name,"c","t")
table.add_column("타입",pokemon_type,"c","t")
```
add row 로 하는것도 있어서
add column 도 있지 않을가 해서 찾아봤는데 있었다
row 로 추가할땐 field name 을 설정해서 
그아래 row로 추가했는데
column 을 할땐 name 까지 한번에 추가한다
그래서 반복문 돌려서 따로 list 만들어서
add column 에 이름, 리스트, align , valign
이었다
align 은 right center left 의 약자 r c l 을넣고
valign 에는 top middle bottom 의 약자 t m b  를 넣는거같다

# exception
예외처리

1. 예외 처리의 필요성
   1) 예외(exception) : 개발자가 직접 처리할 수 있는 문제
   2) 오류(error) : 개발자가 처리할 수 없는 문제
   3) 예외 처리의 목적:
      - 어떤 문제가 발생했을 때 그 문제를 해결해주는 것이 아니라, 발생된 문제로 인해 프로그램이 비정상적으로 종료되는 것을 막고, 사용자에게 발생한 문제에 대해 정보를 전달하기 위함.
2. 예외 처리
    1) 고전적 예외 처리
```python
a = int(input('나누는 수(제수)를 입력하세요 >>> '))
b = int(input('나누어지는 수(피제수)를 입력하세요 >>> '))
if a == 0:
    print('0 으로 나눌 수 없습니다.')
else:
    result = b / a
```
- 어떤 값이든 0으로 나눌 수 없기 때문에 아예 시도할 수 없도록 예외처리를 함.
어떤 문제가 발생할 지 예상할 수 있어야 미리 대비 가능
예상할 수 있더라도 대비할수 없는 경우가 있다.

3. 예외 처리의 종류
```
+------+---------------------+---------------------------------------------+
| 순번 |     예외 클래스     |                     의미                    |
+------+---------------------+---------------------------------------------+
|  1   |    BaseException    |              최상위 예외 클래스             |
|  2   |      Exception      |       대부분 예외 클래스의 슈퍼 클래스       |
|  3   |   ArithmeticError   |          산술 연산에 문제가 있을 때          |
|  4   |    AttributeError   |           잘못된 속성을 참조할 때            |
|  5   |       EOFError      | 파일에서 더 이상 읽어 들일 데이터가 없을 때    |
|  6   | ModuleNotFoundError |           import할 모듈이 없을 때            |
|  7   |  FileNotFoundError  |           존재 하지 않는 파일일 때           |
|  8   |      IndexError     |          잘못된 인덱스를 사용할 때           |
|  9   |      NameError      |        잘못된 이름(변수)을 사용할 때         |
|  10  |     SyntaxError     |               문법이 틀렸을 때              |
|  11  |      TypeError      |    계산하려는 데이터 유형이 잘못되었을 때     |
|  12  |      ValueError     |     계산하려는 데이터 값이 잘못되었을 때      |
+------+---------------------+---------------------------------------------+
```
4. 예외 처리 방식
   1) 모든 예외를 처리하는 방식 -> try / except / 랴ㅜ미ㅣㅛ
   형식 :
try:
    코드 작성 영역
except:
    예외 발생 시 처리 영역
finally:
    언제나 실행되는 영역
1) 특정 예외만 처리하는 방식
    try / except 문을 사용하면 기본적으로 예외의 종류에 상관없이 모든 예외가 처리됨. 하지만 이상에서 본 것처럼, 0으로 나누는 경우와, str자료형을 실수로 바꾸고자 하는 경우에 서로 다른 메시지를 출력해줄 수 있다면, 개발자에게 예외를 처리할 수 있을만한 추가적인 정보를 제공할 수 있음.
   1. 0 으로 나누려고 하는 경우 -> 0으로 나눌수 없습니다.
   2. 정수가 아닌 값을 입력하는 경우 -> 정수만 입력할 수 있습니다.
   등으로 특정 예외에 따른 서로 다른 안내문을 제시한다고 하면,
   except 문 뒤에 처리하고자 하는 예외를 모두 명시하면 됩니다.

3. 예외 메시지 처리하기
    특정 예외가 발생했을 때 메시지를 커스텀해서 사용했지만, 이미 메시지를 가지고있는경우도있습니다. default exception message
형식:
try:
    코드작성영역
except 예외클래스 as 예외메시지:
    예외 발생 시 처리 영역

4. else / finally
    try / except 문에 else / finally를 달 수 있는데,
    else : 예외가 발생하지 않으면 처리되는 구문
    finally : 예외 발생 여부와 관계 없이 맨 마지막에 항상 처리되는 구문

```python
try:
    a = int(input('나누는 수 정수 입력 >> '))
    b = int(input('나누어지는수 정수입력 >> '))
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)
except ValueError as e:
    print(e)
else:
    print(f'b / a = {b/a}')
finally:
    print('프로그램 종료')
```
else 문은 오류가 나지 않으면 실행되는 구간인데
a 에 0 을 넣어도 a 에 0이 들어가는건 문제 없으니
try문 안에서 오류가 발생하지 않는다.
그래서 zerodivisionerror가 일어나지 않는다
try문 안에서 나누지 않으니까
그래서 else로 들어가지만 else 안에서 b/a 를 했을때 zerrodivisionerror가 발생한다.
여기선 예외처리가 되지 않았기 때문에 빨간색으로 콘솔에 출력된다.
그래서 b/a 를 try문에서 result=b/a로 처리하고 else에선 result로 출력한다면 try문 안에서 zerodivisionerror가 발생하기떄문에 예외 처리가 정상적으로 된다.
try를 써버리면 except안 썼을때 오류가 발생하기 때문에 try/except문이 없는상태에서 다양하게 검증해보고 어떤예외 발생하는지 체크후 그 예외들에 대한 except문을 작성해야하고, 정상적으로 처리가 되었을때 else문을 쓸 필요가 있습니다.
5. 강제로 예외를 발생시키기
    어떤 사람이 나이를 정수로 입력받는 프로그램을 사용한다고 가정했을 때 컴퓨터 상으로는 ( 파이썬 상으로는) -1000이 정수이기 때문에 예외가 발생하지 않습니다.(그래서 우리는 0 미만 200초과를 조건문으로 처리했었습니다.)하지만 -1000살이 되는것이 불가능하기 때문에 조건문이 아니라 직접 예외를 발생시켜서 처리하는 방법이 있습니다. -> raise 문
형식:
raise 예외클래스()
또는
raise 예외클래스(예외메시지)

raise의 경우 강제로 예외를 발생시킨다는점에서 주로 사용되는 예외 클래스는 Esception 입니다.

```python
try:
    age = int(input('나이를 입력하세요 >>> '))
    raise Exception('강제로 발생시킨 예외')
except Exception as e:
    print('발생한 예외 메시지는 다음과 같다.')
    print(e)
```
raise 로 넘어가기만하면 바로 예외가 발생해버립니다.
age에 가능한 정수값을 넣어도 예외가 발생하기 때문에 단독으로 처리가 되지 않는다. 그렇다면 조건문을 이용해서 특정 조건일때만 예외로 넘기는 추가 코드가 필요하다.

6. 사용자 정의 예외 클래스 
음수를 입력받을 때 강제로 예외를 발생시키는 예외 클래스를 정의
```python
class NegatioveAgeError(Exception):     # Exception 클래스 상속 받았다는 의미
    """사용자 정의 예외 클래스 : 나이가 음수일때 발생"""
    pass
try:
    age = int(input('나이를 입력 >> '))
    if age < 0:
        raise NegatioveAgeError('나이는 음수일 수 없습니다.')
except NegatioveAgeError as e:
    print('발생한 예외 메시지는 다음과 같다')
    print(e)
else:
    print(f'당신의 나이는 {age} 살이다.')
```
사용자 정의 예외 클래스르 만들어서 조건이 맞지 않을때 예외를 발생시킨다.

getattr()의 두 번째 argument는 인스턴스 변수명을 받습니다 -> 그 데이터를 str으로 받습니다.
`getattr(person1, 'name')`
getattr(객체명, '속성명')
vars(객체명) - 특정 객체의 속성명-속성값 쌍을 dictionary 형태의 key-value 쌍으로 변환





























